name = "tmdb-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

# Uncomment to use a custom domain
# routes = [
#   { pattern = "yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# Workers configuration
workers_dev = true

[env.production]
name = "tmdb-proxy"
